### ISSUE TITLE
Need to Fix version 1

### ISSUE THREAD

**Issue by Kidkender** [toanhhg123/Proxy_Manager#1]
### **Some problem from guest:** 
1. Can order 
2. Deploy 1 proxy to website
3. Add Column API proxy  
4. Auto choose IP turn area

**In back-end : @ngocKhoaIT** 
1. Create table Proxy_Area: id, Country, City, Date_Update 
2. Update table Product_residential_ipv4 
-   proxy_id SERIAL PRIMARY KEY,
    ipv6 VARCHAR(39),
    proxy_port INT,
    proxy_port_v6 INT,
    system VARCHAR(255),
    public_ip VARCHAR(15),
    public_ip_v6 VARCHAR(39),
    resetting BOOLEAN,
    ppp VARCHAR(255),
    ppp_tty VARCHAR(255)
    price
-  add field: API_link, id_area_proxy (reference to Proxy_Area) , isActive (true/false) 
3. Login with username and password (Update authen)
4. Create table IP_by_Port : id, IP,port (reference table  **Product_residential_ipv4** field port) (data call from API guest API 1: 
-               URL: [host]:[port]/proxy/public_ip?proxy=[proxy ip:port]
-               Method: GET

**In Front-end: @toanhhg123** 

1. Custom client for Guest/Customer 

2. Get All proxy to component manager Proxy depen (API get All proxy from guest)
                                                                          URL: [host]:[port]/proxy_list
                                                                          Method: GET
3. Get 1 proxy for deploying

**Comment by ngocKhoaIT** [comment]
Done
