### ISSUE TITLE
Need to Fix version 2

### ISSUE THREAD

**Issue by Kidkender** [toanhhg123/Proxy_Manager#2]
Backend @ngocKhoaIT 

1. Write API Update/Check status proxy (active or not active) true | false
2. Write API get all proxy from link api of guest to save Db project team
3. Get proxy/IP by city

**Comment by Kidkender** [comment]
FrontEnd @toanhhg123 

1. Add footer in client guest/customer
2. Fix button in menu 'Bảng điều khiển' / 'Lịch sử nạp tiền'
3. In component Buy proxy V4 : add field input 'City'/ Price and total money 
4. In menu or sidebar add 1 component has name 'Contact admin'

**Comment by toanhhg123** [comment]
oke
