### ISSUE TITLE
Fix all Database and Flow Project V_1

### ISSUE THREAD

**Issue by Kidkender** [toanhhg123/Proxy_Manager#3]
**Back-end: @ngocKhoaIT** 

1. Modify Table Area to Table Proxy_Area: 
 - ID, Country, City, Link_Area, Link_ListProxy, Price 
2.  In Table Product_Presidential_IPV4  
-  Rename to Proxy_Presidential
- Delete field: category_id / description/ price/ api_link/ is_active/ 
- Add column isOdered ( true/false)

Front-end: @toanhhg123 
1.  Hiden menu 4G/ list menu/ submenu/ Sercurity/ metod_Security/ method_connection/Product
2. Create UI: get list proxy is_active at 1 area
3. Modify screen : Form Proxy Area same table Proxy_Area
**When done task, commnent "Done" !!**

**Comment by ngocKhoaIT** [comment]
Done
